CREATE DATABASE IF NOT EXISTS meme_db;
USE meme_db;

CREATE TABLE IF NOT EXISTS memes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    image MEDIUMBLOB NOT NULL,
    top_text TEXT NOT NULL,
    bottom_text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);